Security Configuration
IF-128-Java/course_evaluation_analytics pull request #1
Opened 2021-09-02 07:44 UTC by James-Koval

2021-09-02 07:50 UTC, Forfend requested changes

2021-09-02 07:50 UTC, Forfend commented on src/main/java/ita/softserve/course_evaluation_analytics/repository/impl/UsersRepositoryImpl.java
> +    public JdbcTemplate jdbcTemplate;
```NamedParameterJdcbTemplate```

2021-09-02 07:50 UTC, Forfend commented on src/main/java/ita/softserve/course_evaluation_analytics/repository/impl/UsersRepositoryImpl.java
> +        String sql = "SELECT * FROM users u WHERE u.email = ?1";
extract query into ```query.properties```

2021-09-02 07:50 UTC, Forfend commented on src/main/java/ita/softserve/course_evaluation_analytics/configuration/SpringConfig.java
> +        dataSource.setUrl("jdbc:postgresql://localhost:5432/course_evaluation");
take those values from env.variable

2021-09-02 07:50 UTC, Forfend commented on src/main/java/ita/softserve/course_evaluation_analytics/entity/Users.java
> +//    private Group group;
you do not need group, course, etc

2021-09-06 19:38 UTC, yapollo2002 approved these changes

2021-09-06 19:40 UTC, merged